### ISSUE TITLE
I always get previous result back everytime I run the app.

### ISSUE THREAD

**Issue by ZabuKyaw99** [40437404/DevOps_SET09623#17]

**Comment by bagu6tt6** [comment]
It is because of the caches which is saved by running the previous un-updated app. To get the proper results 
1. delete the app container and the latest images
2. then rebuild, compile and package the app
3. run the docker-compose.yml after the package is finish
4.wait for the result to appear
So you will get the coded results. Make sure you follow above steps to appear results correctly
